// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlmmftfcqcvjmzazdhbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsbW1mdGZjcWN2am16YXpkaGJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MDQzMzMsImV4cCI6MjA1ODM4MDMzM30.ca_sEKd6QjmLyCADIl1b6dUBfbWhHDMRjWDnjUYPvGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);